name: ml_lecture
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=3.1.7
  - keras=2.4.3
  - matplotlib=3.4.2
  - numpy=1.20.3
  - pandas=1.3.3
  - pip=21.2.2
  - python=3.8.11
  - seaborn=0.11.2
  - tensorflow=2.3.0
  - xgboost=1.5.0
  - lightgbm=3.3.1
  - pip:
    - plotnine==0.8.0
    - scikit-learn==1.0
    - dalex==1.4.1
    - nb-black

